server:
    port: 8081

spring:
    datasource:
        url: jdbc:mysql://120.77.203.216/gyt?useUnicode=true&characterEncoding=gbk&autoReconnect=true&failOverReadOnly=false&allowMultiQueries=true&serverTimezone=Asia/Shanghai
        #        url: jdbc:mysql://localhost/test3?useUnicode=true&characterEncoding=gbk&autoReconnect=true&failOverReadOnly=false&allowMultiQueries=true&serverTimezone=Asia/Shanghai
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: 123456
